// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/1/2025, 8:50:16 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/joel-henry/projects/tte/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/joel-henry/projects/tte/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/joel-henry/projects/tte/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/joel-henry/projects/tte/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/joel-henry/projects/tte/plugins/**/*.{js,ts,mjs}","/home/joel-henry/projects/tte/composables/**/*.{js,ts,mjs}","/home/joel-henry/projects/tte/utils/**/*.{js,ts,mjs}","/home/joel-henry/projects/tte/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/joel-henry/projects/tte/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/joel-henry/projects/tte/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/joel-henry/projects/tte/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;